services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: mongo_db
      MONGO_INITDB_ROOT_PASSWORD: your_password
      MONGO_INITDB_ROOT_USERNAME: your_name
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    ports:
      - 6379:6379
